MODULE = actions

include ../../../buildsys.mk
include ../../../buildsys.module.mk

CPPFLAGS += -I../..
LIBS += -lm -lssh2
SRCS = customscript.c cisco-nullroute.c vyatta-nullroute.c nullroute.c email.c
